---

- name: Provisionning VM
  hosts: all
  remote_user: root
  gather_facts: true
  become: yes

  roles:
   - Docker

  #  - name: install Vim
  #    yum:
  #     name: vim
  #     state: latest

- name: init swarm mode
  hosts: swarmmanager
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo
  
  roles: 
    - Docker_Swarm 
  
  # tasks:
  #   - name: docker compose elasticsearch
  #     copy:
  #      src: "docker-compose.yml"
  #      dest: "/tmp/docker-compose.yml"
  #   - name: create service with docker-compose
  #     shell: "docker stack deploy --compose-file /tmp/docker-compose.yml elastic"

- name: add workers
  hosts: swarmworkers
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo

  roles:
    - Docker_Swarm_Workers


...
