---

- name: Provisionning VM
  hosts: all
  remote_user: root
  gather_facts: true
  become: yes

  roles:
   - Docker
   - Java

- name: init swarm mode
  hosts: swarmmanager
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo
  
  roles: 
    - Docker_Swarm 
    - Elasticsearch
  

- name: add workers
  hosts: swarmworkers
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo

  roles:
    - Docker_Swarm_Workers

# - name: add p
#   hosts: monitserver
#   remote_user: root
#   gather_facts: true
#   become: yes
#   become_method: sudo

#   roles:
#     - Postfix



...
